service:
  name: serverless-aws-nodejs-ecmascript-flow

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-flow
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  first:
    handler: first.hello
    events:
      - http:
          method: get
          path: first
